### ISSUE TITLE
Error: please fill out both fields with unique info

### ISSUE THREAD

**Issue by janetmango** [Lamikins/HabitiFit#2] opened 2015-09-02 23:10 UTC
Since the changeover to HabitiFit, my account was working correctly, but then lost my Habitica account info.  I re-input my API and User ID and got the error above. 

Thanks.

**Comment by Lamikins** [comment] 2015-09-02 23:30
This is caused by a small error in item.js— it should be fixed now.  Let me
know if it still doesn't work.

**Comment by janetmango** [comment] 2015-09-02 23:33
It works fine now.  Thanks.

**Closed** 2015-09-02 23:36 UTC
